@host=http://localhost:8087/matchboxv3/fhir



### Check if server is available
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost


###
GET {{host}}/StructureDefinition  HTTP/1.1



###
### verify that StructureDefinition is there on configured on matchbox
GET {{host}}/StructureDefinition?url=http://smart.who.int/icvp/StructureDefinition/ICVP HTTP/1.1

###
### verify that StructureDefinition is there on configured on matchbox
GET {{host}}/StructureDefinition?url=http://smart.who.int/icvp/StructureDefinition/ICVP HTTP/1.1



### Upload the StructureMap

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./ICVPClaimtoIPS.map





###
PUT {{host}}/StructureDefinition/ICVPMin
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPMin.json


###
PUT {{host}}/StructureDefinition/ICVP
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVP.json




###
PUT {{host}}/StructureDefinition/ICVPVaccineDetails
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPVaccineDetails.json




###
PUT {{host}}/StructureDefinition/ICVPEvent
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPEvent.json


###
PUT {{host}}/StructureDefinition/ICVPImmunization
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPImmunization.json



###
PUT {{host}}/StructureDefinition/ICVPMinVaccineDetails
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPMinVaccineDetails.json


###
PUT {{host}}/StructureDefinition/ICVPSD
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPSD.json


###
PUT {{host}}/StructureDefinition/ICVPVaccineDetailsSD
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPVaccineDetailsSD.json


















#######################################







POST {{host}}/$validate?profile=http://smart.who.int/icvp/StructureDefinition/ICVP HTTP/1.1
Accept: application/json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVP.json








###
PUT {{host}}/StructureMap/DVCClaimtoDVCLM
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-DVCClaimtoDVCLM.json


###
PUT {{host}}/StructureMap/ICVPClaimtoICVPLM
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPClaimtoICVPLM.json


###
PUT {{host}}/StructureMap/ICVPClaimtoIPS
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPClaimtoIPS.json


###
PUT {{host}}/StructureMap/ICVPLMtoICVPClaim
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPLMtoICVPClaim.json


###
PUT {{host}}/StructureMap/ICVPLMToIPS
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPLMToIPS.json


###
PUT {{host}}/StructureMap/ICVPQRtoICVPClaim
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPQRtoICVPClaim.json


###
PUT {{host}}/StructureMap/ICVPQRtoICVPLM
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-ICVPQRtoICVPLM.json


###
PUT {{host}}/StructureMap/PreQualDBtoProductLM
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureMap-PreQualDBtoProductLM.json


###
### Transform file1.json using sm1 (with sm2/sm3 already available)
POST {{host}}/StructureMap/ICVPClaimtoIPS/$transform
Accept: application/fhir+json
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "srcMap",
      "valueString": "/* Paste full IMMZCQRToPatient.fml text here */"
    },
    {
      "name": "content",
      "resource":
        {
  "6" : 1754582715,
  "1" : "XXK",
  "-260" : {
    "-6" : {
      "n" : "Cristina Rodriguez",
      "dob" : "1994-10-13",
      "v" : {
        "vp" : "YellowFeverProductd2c75a15ed309658b3968519ddb31690",
        "dt" : "2020-11-15",
        "bo" : "A1234",
        "vls" : "2020-11-15",
        "vle" : "2025-11-15",
        "cn" : "Juan Castro",
        "is" : "MINSALUD"
      },
      "s" : "male",
      "ntl" : "CHL",
      "nid" : "126008-7",
      "ndt" : "NI",
      "gn" : "Parent/Antonio Rojas"
    }
  }
}

    }
  ]
}

####

### Claim/Payload -> IPS using ICVPClaimtoIPS
POST {{host}}/StructureMap/ICVPClaimtoIPS/$transform
Accept: application/fhir+json
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "content",
      "resource": {
        "resourceType": "Parameters",
        "parameter": [
          { "name": "meta.6", "valueInteger": 1754582715 },
          { "name": "meta.1", "valueString": "XXK" },

          { "name": "n",   "valueString": "Cristina Rodriguez" },
          { "name": "dob", "valueDate":   "1994-10-13" },
          { "name": "s",   "valueString": "male" },
          { "name": "ntl", "valueString": "CHL" },
          { "name": "nid", "valueString": "126008-7" },
          { "name": "ndt", "valueString": "NI" },
          { "name": "gn",  "valueString": "Parent/Antonio Rojas" },

          { "name": "v.vp",  "valueString": "YellowFeverProductd2c75a15ed309658b3968519ddb31690" },
          { "name": "v.dt",  "valueDate":   "2020-11-15" },
          { "name": "v.bo",  "valueString": "A1234" },
          { "name": "v.vls", "valueDate":   "2020-11-15" },
          { "name": "v.vle", "valueDate":   "2025-11-15" },
          { "name": "v.cn",  "valueString": "Juan Castro" },
          { "name": "v.is",  "valueString": "MINSALUD" }
        ]
      }
    }
  ]
}

#############################################################




###
###
PUT {{host}}/StructureDefinition/Bundle-uv-ips-ICVP
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-Bundle-uv-ips-ICVP.json


###
PUT {{host}}/StructureDefinition/Composition-uv-ips-ICVP
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-Composition-uv-ips-ICVP.json



###
PUT {{host}}/StructureDefinition/ICVP
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVP.json


###
PUT {{host}}/StructureDefinition/ICVPEvent
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPEvent.json


###
PUT {{host}}/StructureDefinition/ICVPImmunization
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPImmunization.json



###
PUT {{host}}/StructureDefinition/ICVPMinVaccineDetails
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPMinVaccineDetails.json


###
PUT {{host}}/StructureDefinition/ICVPSD
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPSD.json


###
PUT {{host}}/StructureDefinition/ICVPVaccineDetails
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPVaccineDetails.json


###
PUT {{host}}/StructureDefinition/ICVPVaccineDetailsSD
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./StructureDefinition-ICVPVaccineDetailsSD.json






###

POST {{host}}/StructureMap/$transform?source=http://smart.who.int/icvp/StructureMap/ICVPClaimtoIPS
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./icvp.json



